// Post-build: write dist/sw.js (Lens master plan, Card D.1).
//
// Hand-rolled instead of @vite-pwa/astro: that integration's peer range stops
// at Astro 5 and this repo is on Astro 6. The worker is small enough to own:
//   - precache the engine shell (home, privacy, their CSS/JS, the Lens chunks)
//   - /api/*            → never touched (network only; nothing about a scan is cached here)
//   - navigations       → network first, cached copy when offline
//   - /_astro/* hashed  → cache first
//   - other same-origin → stale-while-revalidate (CSS, images, the barcode wasm)
//   - Google Fonts      → stale-while-revalidate
// The cache name carries a hash of the precache contents, so every deploy that
// changes the shell retires the old cache on activate.
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIST = path.join(ROOT, 'dist');
if (!existsSync(path.join(DIST, 'index.html'))) {
  console.error('build_sw: dist/index.html missing — run `astro build` first.');
  process.exit(1);
}

// Academy / DIY / directory chunks stay out of the engine's install payload.
const NOT_SHELL = /^(Directory|Quiz|QuizLbga|quizzes)\./;
const astroJs = readdirSync(path.join(DIST, '_astro')).filter((f) => f.endsWith('.js') && !NOT_SHELL.test(f));

// Same-origin assets the two shell pages reference directly.
const pages = ['index.html', 'privacy/index.html'];
const referenced = new Set();
for (const page of pages) {
  const html = readFileSync(path.join(DIST, page), 'utf8');
  for (const m of html.matchAll(/(?:href|src)="(\/(?:_astro|css|js|images)\/[^"#?]+)"/g)) referenced.add(m[1]);
}

const precache = [...new Set([
  '/', '/privacy/', '/manifest.webmanifest', '/images/pwa/icon-192.png',
  ...referenced,
  ...astroJs.map((f) => `/_astro/${f}`),
])].sort();

const fileFor = (url) => path.join(DIST, url.endsWith('/') ? `${url}index.html` : url);
const missing = precache.filter((u) => !existsSync(fileFor(u)));
if (missing.length) {
  console.error('build_sw: precache entries missing from dist:\n  ' + missing.join('\n  '));
  process.exit(1);
}

const hash = createHash('sha256');
for (const u of precache) hash.update(u).update(readFileSync(fileFor(u)));
const version = readFileSync(path.join(ROOT, 'VERSION'), 'utf8').trim();
const cacheName = `recyclopedia-${version}-${hash.digest('hex').slice(0, 10)}`;

const sw = `// Generated by scripts/build_sw.mjs — do not edit.
const CACHE = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(PRECACHE.map((url) => new Request(url, { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('recyclopedia-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

function put(request, response) {
  if (response && (response.ok || response.type === 'opaque')) {
    const copy = response.clone();
    caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
  }
  return response;
}

async function networkFirst(request) {
  try {
    return put(request, await fetch(request));
  } catch (err) {
    const cached = await caches.match(request, { ignoreSearch: true });
    return cached || (await caches.match('/')) || Response.error();
  }
}

async function cacheFirst(request) {
  return (await caches.match(request)) || put(request, await fetch(request));
}

async function staleWhileRevalidate(request) {
  const cached = await caches.match(request);
  const fresh = fetch(request).then((response) => put(request, response)).catch(() => cached || Response.error());
  return cached || fresh;
}

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  if (url.origin === self.location.origin) {
    if (url.pathname.startsWith('/api/')) return;              // network only — scans are never cached here
    if (url.pathname === '/sw.js') return;
    if (request.mode === 'navigate') return event.respondWith(networkFirst(request));
    if (url.pathname.startsWith('/_astro/')) return event.respondWith(cacheFirst(request));
    return event.respondWith(staleWhileRevalidate(request));
  }
  if (FONT_HOSTS.includes(url.hostname)) event.respondWith(staleWhileRevalidate(request));
});
`;

writeFileSync(path.join(DIST, 'sw.js'), sw);
console.log(`build_sw: ${precache.length} precache entries → dist/sw.js (${cacheName})`);
