// The Florida drop-off experiment (Pit Board D). The list is generated by
// scripts/frs_national.py; these tests hold the promises the page makes.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { ROOT } from './_load.mjs';

const data = JSON.parse(readFileSync(path.join(ROOT, 'src', 'data', 'dropoff-fl.json'), 'utf8'));
const TIERS = new Set(['scrap_yard', 'public_drop_off']);

test('only Florida, only the two classes Luiz cleared, marked as an experiment', () => {
  assert.deepEqual(data.scope, ['FL']);
  assert.equal(data.experiment, true);
  assert.ok(data.total > 0 && data.total === data.sites.length);
  for (const s of data.sites) assert.ok(TIERS.has(s.publish_tier), `${s.name}: ${s.publish_tier}`);
});

test('every site carries the evidence it is listed on', () => {
  for (const s of data.sites) {
    assert.ok(s.registry_id && s.name, 'registry id and name');
    assert.ok(s.class_basis, `${s.name}: no class_basis`);
    if (s.publish_tier === 'public_drop_off') {
      assert.equal(s.operator_kind, 'local_government', `${s.name}: drop-off without a local-government basis`);
      assert.notEqual(s.operator_basis, 'none');
    }
  }
});

test('no duplicate sites', () => {
  const ids = data.sites.map((s) => s.registry_id);
  assert.equal(new Set(ids).size, ids.length);
});

test('the built page never claims a site is open, and always says call first', () => {
  const page = path.join(ROOT, 'dist', 'dropoff', 'florida', 'index.html');
  if (!existsSync(page)) throw new Error('page not built — run `npm run build` first (or `npm test`).');
  const html = readFileSync(page, 'utf8');
  assert.doesNotMatch(html, /open to the public/i);
  assert.match(html, /Call first/);
  assert.match(html, /We have not confirmed any of these places/);
  assert.match(html, /name="robots" content="noindex"/);
});
